/**
 * Application version - auto-generated at build time
 * Generated by scripts/generate-version.js
 */
export const APP_VERSION = 'f724296'

export function getAppVersion(): string {
  return APP_VERSION
}
