#!/usr/bin/env node

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

try {
  // Get the git commit hash (last 7 characters)
  const gitHash = execSync('git rev-parse --short=7 HEAD', { encoding: 'utf-8' }).trim();

  // Write to src/lib/version.ts
  const versionFilePath = path.join(__dirname, '..', 'src', 'lib', 'version.ts');
  const versionContent = `/**
 * Application version - auto-generated at build time
 * Generated by scripts/generate-version.js
 */
export const APP_VERSION = '${gitHash}'

export function getAppVersion(): string {
  return APP_VERSION
}
`;
  fs.writeFileSync(versionFilePath, versionContent, 'utf-8');

  console.log(`✓ Generated src/lib/version.ts with version: ${gitHash}`);
} catch (error) {
  console.error('Error generating version file:', error.message);

  // Write 'dev' as fallback
  const versionFilePath = path.join(__dirname, '..', 'src', 'lib', 'version.ts');
  const versionContent = `/**
 * Application version - auto-generated at build time
 * Generated by scripts/generate-version.js
 */
export const APP_VERSION = 'dev'

export function getAppVersion(): string {
  return APP_VERSION
}
`;
  fs.writeFileSync(versionFilePath, versionContent, 'utf-8');

  console.log('✓ Generated src/lib/version.ts with fallback version: dev');
}
